'use strict';
// Embedded CC0 recordings: Bottle Shattering by spookymodem (Freesound 202093),
// and Impact Sounds by Kenney. Sources and licenses are included at the end of this file.
let ac,master,compressor,noiseBuffer,muted=false,lastClink=0,reverb,wetBus;
function initAudio(){if(ac){ac.resume();return audioLoading;}ac=new(window.AudioContext||window.webkitAudioContext)();master=ac.createGain();master.gain.value=.55*.6;compressor=ac.createDynamicsCompressor();compressor.threshold.value=-12;compressor.knee.value=12;compressor.ratio.value=4;compressor.attack.value=.004;compressor.release.value=.16;master.connect(compressor);compressor.connect(ac.destination);noiseBuffer=ac.createBuffer(1,ac.sampleRate*2,ac.sampleRate);const data=noiseBuffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;
reverb=ac.createConvolver();const ir=ac.createBuffer(2,Math.floor(ac.sampleRate*.28),ac.sampleRate);for(let c=0;c<2;c++){let a=ir.getChannelData(c);for(let i=0;i<a.length;i++){const t=i/ac.sampleRate;a[i]=(Math.random()*2-1)*Math.exp(-t*27)*.09;if(i<ac.sampleRate*.015)a[i]=0;}}reverb.buffer=ir;wetBus=ac.createGain();wetBus.gain.value=.10;reverb.connect(wetBus);wetBus.connect(master);audioLoading=Promise.all(Object.entries(embeddedAudio).map(async([key,b64])=>{const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));try{soundBuffers[key]=await ac.decodeAudioData(bytes.buffer);}catch{}}));return audioLoading;}
function channel(x){const pan=ac.createStereoPanner();pan.pan.value=THREE.MathUtils.clamp(x/5,-.8,.8);pan.connect(master);pan.connect(reverb);return pan;}
function playSample(key,x,gain=1,rate=1,delay=0,offset=0,duration){if(!ac||muted||!soundBuffers[key])return;const source=ac.createBufferSource(),level=ac.createGain(),pan=channel(x);source.buffer=soundBuffers[key];source.playbackRate.value=rate*(slow?.72:1);level.gain.value=gain;source.connect(level);level.connect(pan);const t=ac.currentTime+delay;if(duration)source.start(t,offset,duration);else source.start(t,offset);source.onended=()=>{source.disconnect();level.disconnect();pan.disconnect();};}
function tone(dest,freq,t,dur,amp,type='sine'){const o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(freq*.76,t+dur);g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(amp,t+.003);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(dest);o.start(t);o.stop(t+dur+.01);o.onended=()=>{o.disconnect();g.disconnect();};}
function noise(dest,t,dur,freq,amp,kind='highpass'){const s=ac.createBufferSource();s.buffer=noiseBuffer;const f=ac.createBiquadFilter(),g=ac.createGain();f.type=kind;f.frequency.value=freq;f.Q.value=.6;g.gain.setValueAtTime(amp,t);g.gain.exponentialRampToValueAtTime(.001,t+dur);s.connect(f);f.connect(g);g.connect(dest);s.start(t,rnd(0,.5),dur);s.onended=()=>{s.disconnect();f.disconnect();g.disconnect();};}
function crash(x,speed){if(!ac||muted)return;playSample('shatter',x,.60+Math.min(.24,speed*.012),rnd(.92,1.07));playSample('heavy'+(Math.random()*3|0),x,.16,rnd(.94,1.03));}
function clink(x,speed){if(!ac||muted||ac.currentTime-lastClink<.055)return;lastClink=ac.currentTime;playSample('light'+(Math.random()*3|0),x,Math.min(.28,.055+speed*.025),rnd(.87,1.18));}
function smallCrack(x){if(!ac||muted)return;playSample('shatter',x,.30,rnd(1.08,1.3),0,0,.12);playSample('light'+(Math.random()*3|0),x,.13,1.1,.025);}
function whoosh(){if(!ac||muted)return;const p=channel(0);noise(p,ac.currentTime,.10,550,.07,'bandpass');setTimeout(()=>p.disconnect(),250);}
