'use strict';
const raycaster=new THREE.Raycaster(),aim=new THREE.Vector2(0,0),target=new THREE.Vector3(),aimPlane=new THREE.Plane(new THREE.Vector3(0,0,1),0);
const ballMaterial=new THREE.MeshStandardMaterial({color:0xcbd1cf,metalness:1,roughness:.12});const ballGeo=new THREE.SphereGeometry(.105,32,24);
function fire(power){if(!started)return;try{initAudio();}catch{}raycaster.setFromCamera(aim,camera);if(!raycaster.ray.intersectPlane(aimPlane,target))return;const origin=new THREE.Vector3(.24,2.3,9);let delta=target.clone().sub(origin),speed=8+power*.29,flight=delta.length()/speed;let vel=delta.divideScalar(flight);vel.y+=.5*9.81*flight;let mesh=new THREE.Mesh(ballGeo,ballMaterial);mesh.castShadow=true;scene.add(mesh);let body=new CANNON.Body({mass:.28,material:steelPhys,shape:new CANNON.Sphere(.105),position:new CANNON.Vec3(origin.x,origin.y,origin.z),velocity:new CANNON.Vec3(vel.x,vel.y,vel.z),linearDamping:.02,angularDamping:.25,collisionFilterGroup:2,collisionFilterMask:31});body.ball=true;world.addBody(body);balls.push({mesh,body,age:0});shots++;$('shots').textContent=String(shots).padStart(2,'0');whoosh();while(balls.length>12){let o=balls.shift();scene.remove(o.mesh);world.removeBody(o.body);}}
let charging=false,chargeStart=0,pointerID=null;function setAim(e){let rect=renderer.domElement.getBoundingClientRect();aim.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);$('cross').style.left=e.clientX+'px';$('cross').style.top=e.clientY+'px';}
renderer.domElement.addEventListener('pointermove',setAim);renderer.domElement.addEventListener('pointerdown',e=>{if(!started||e.button>0)return;setAim(e);charging=true;chargeStart=performance.now();pointerID=e.pointerId;renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointerup',e=>{if(!charging)return;setAim(e);charging=false;fire(Math.min(100,+$('power').value+(performance.now()-chargeStart)/24));$('charge').style.width='0';});renderer.domElement.addEventListener('pointercancel',()=>{charging=false;$('charge').style.width='0';});
$('power').oninput=()=>{$('powerLabel').textContent=$('power').value+'%';};function toggleSlow(){slow=!slow;$('slow').classList.toggle('on',slow);$('slow').textContent=slow?'SLOW MOTION · ON':'SLOW MOTION';} $('slow').onclick=toggleSlow;$('reset').onclick=rebuild;$('sound').onclick=()=>{initAudio();muted=!muted;master.gain.setTargetAtTime(muted?0:+$('volume').value*.6,ac.currentTime,.02);$('sound').textContent=muted?'SOUND OFF':'SOUND ON';};$('volume').oninput=()=>{if(ac)master.gain.setTargetAtTime(muted?0:+$('volume').value*.6,ac.currentTime,.02);};$('start').onclick=async()=>{$('start').disabled=true;try{await initAudio();}catch(e){$('sound').textContent='SOUND UNAVAILABLE';}started=true;$('intro').style.display='none';};document.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;if(e.key.toLowerCase()==='r')rebuild();if(e.code==='Space'){e.preventDefault();toggleSlow();}});
let toastTimer;function showToast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2100);}
function resize(){const w=innerWidth,h=innerHeight;camera.aspect=w/h;baseCamera.set(focus.x,focus.y+1.6,(w/h<.85?29:24)/zoom);camera.position.copy(baseCamera);camera.lookAt(focus);camera.updateProjectionMatrix();renderer.setSize(w,h);}addEventListener('resize',resize);resize();renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();setAim(e);raycaster.setFromCamera(aim,camera);const p=new THREE.Vector3();raycaster.ray.intersectPlane(aimPlane,p);const oldZoom=zoom;zoom=THREE.MathUtils.clamp(zoom*Math.exp(-e.deltaY*.0012),1,2.6);if(zoom===1)focus.set(0,5.1,0);else if(e.deltaY<0){focus.lerp(p,1-oldZoom/zoom);focus.x=THREE.MathUtils.clamp(focus.x,-3,3);focus.y=THREE.MathUtils.clamp(focus.y,1,9);}resize();},{passive:false});
rebuild();$('start').disabled=false;$('start').textContent='STEP UP & THROW';let prev=performance.now(),acc=0;const step=1/120,maxPhysicsSteps=8;
// Shadows are re-rendered only while something moves.
renderer.shadowMap.autoUpdate=false;let shadowFrames=3;$('reset').addEventListener('click',()=>shadowFrames=3);addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r')shadowFrames=3;});
// Dynamic resolution: drop pixel ratio when frames get slow, raise it back when there is headroom.
const maxPR=Math.min(devicePixelRatio,1.5),minPR=Math.min(1,maxPR);let pixelRatio=maxPR,prCeiling=maxPR,frameEMA=16.7,prChangedAt=0,prRaisedAt=-1e9;
function adaptQuality(now,dtSec){frameEMA+=(Math.min(100,dtSec*1000)-frameEMA)*.06;if(now-prChangedAt<1200)return;if(frameEMA>21&&pixelRatio>minPR){if(now-prRaisedAt<3500)prCeiling=Math.max(minPR,pixelRatio-.1);pixelRatio=Math.max(minPR,pixelRatio-.15);renderer.setPixelRatio(pixelRatio);prChangedAt=now;}else if(frameEMA<17.6&&pixelRatio<prCeiling&&now-prChangedAt>4000){pixelRatio=Math.min(prCeiling,pixelRatio+.1);renderer.setPixelRatio(pixelRatio);prChangedAt=prRaisedAt=now;}}
const vec=new THREE.Vector3(),normal=new THREE.Vector3(),invQ=new THREE.Quaternion(),up=new THREE.Vector3(0,1,0);
// Sleeping stack bodies never notice that their support moved or broke away -> they hang in the air. Wake sleeping bottles/planks above anything that moves.
const stackBodies=[];function wakeStack(){stackBodies.length=0;for(const o of bottles)stackBodies.push(o.body);for(const o of planks)stackBodies.push(o.body);for(const m of stackBodies){if(m.sleepState===2||m.velocity.lengthSquared()<.09)continue;for(const s of stackBodies)if(s.sleepState===2&&s.position.y>m.position.y-.6&&Math.abs(s.position.x-m.position.x)<3&&Math.abs(s.position.z-m.position.z)<2.5)s.wakeUp();}}
// cannon has no rolling resistance: slow, low bodies (rolling bottles, balls, rocking shards) would never fall asleep. Bleed off their last bit of motion.
function settleDamping(){for(const b of world.bodies){if(b.mass===0||b.sleepState===2)continue;const v=b.velocity.lengthSquared(),w=b.angularVelocity.lengthSquared();if(v<.16&&w<1){b.velocity.scale(.985,b.velocity);b.angularVelocity.scale(.97,b.angularVelocity);}if(b.ball&&b.position.y<.2){b.velocity.scale(.993,b.velocity);b.angularVelocity.scale(.993,b.angularVelocity);}if(b.position.y<-.6&&!b.bottle){b.velocity.set(0,0,0);b.sleep();}}}
// Debris (body group 8) collides with balls, table and shelves, never with bottles: a shard spawns overlapping its own
// bottle, and resolving that overlap used to launch the bottle into the air.
// Light shards jitter on top of heavy bottles and never sleep. After a short flight a shard only collides with the table
// and balls, so it drops onto the table, falls asleep and gets baked into static batches (no physics, one draw call per material).
const DEBRIS_MAX=90,DEBRIS_FLIGHT=1;
function settleDebris(dt){let removed=false;for(let i=0;i<debris.length;i++){const d=debris[i],b=d.body;if(d.enableAt)continue;d.age=(d.age||0)+dt;if(d.age>DEBRIS_FLIGHT&&b.collisionFilterMask!==6){b.collisionFilterMask=6;b.wakeUp();}if(b.sleepState!==2||b.collisionFilterMask!==6)continue;world.removeBody(b);d.mesh.position.copy(b.position);d.mesh.quaternion.copy(b.quaternion);bakeStatic(d.mesh);debris[i]=null;removed=true;}
if(removed)debris=debris.filter(Boolean);while(debris.length>DEBRIS_MAX){const d=debris.shift();world.removeBody(d.body);clearObject(d.mesh);}}
function tickPhysics(dt){simTime+=dt;wakeStack();for(const d of debris)if(d.enableAt&&simTime>=d.enableAt){d.body.collisionFilterMask=22;d.enableAt=0;}world.step(dt);settleDamping();for(const [ob,hit]of breakQueue)damageBottle(ob,hit);breakQueue.clear();}
function animate(now){requestAnimationFrame(animate);const realDt=Math.min((now-prev)/1000,.06);prev=now;const dt=started?realDt*(slow?.23:1):0;acc=Math.min(acc+dt,step*maxPhysicsSteps);let physicsSteps=0;while(acc>=step&&physicsSteps<maxPhysicsSteps){tickPhysics(step);acc-=step;physicsSteps++;}if(physicsSteps)settleDebris(physicsSteps*step);adaptQuality(now,realDt);for(const ob of bottles){updateFluid(ob,dt);syncBottleMass(ob);}for(const o of planks){o.mesh.position.copy(o.body.position);o.mesh.quaternion.copy(o.body.quaternion);}for(const o of debris){o.mesh.position.copy(o.body.position);o.mesh.quaternion.copy(o.body.quaternion);}for(const o of balls){o.mesh.position.copy(o.body.position);o.mesh.quaternion.copy(o.body.quaternion);}updateDrops(dt);shake*=.88;camera.position.copy(baseCamera);camera.position.x+=rnd(-shake,shake);camera.position.y+=rnd(-shake,shake);camera.lookAt(focus);if(charging){const c=Math.min(100,+$('power').value+(performance.now()-chargeStart)/24);$('charge').style.width=c+'%';}let anyAwake=false;for(const bd of world.bodies)if(bd.mass>0&&bd.sleepState!==2){anyAwake=true;break;}if(anyAwake||shadowFrames>0){renderer.shadowMap.needsUpdate=true;shadowFrames--;}renderer.render(scene,camera);}
requestAnimationFrame(animate);
window.bottleLab={getState:()=>({broken,shots,fragments:debris.length,drops:drops.length,puddles:puddles.length,slow,started,audioReady:Object.keys(soundBuffers),bottles:bottles.map(b=>({name:brands[b.idx].name,height:brands[b.idx].h,damage:b.damage,perforations:b.perforations||0,parts:b.parts.filter(p=>p.attached).length,holes:b.holes.length,fluid:b.fluid,drift:b.body.position.distanceTo(b.initial)}))}),throwAt:(index,p=35)=>{const t=new THREE.Vector3().copy(bottles[index].body.position).project(camera);aim.set(t.x,t.y);fire(p);},aimAndThrow:(x,y,p=35)=>{aim.set(x,y);fire(p);},advance:(seconds)=>{for(let i=0;i<seconds*120;i++){tickPhysics(step);for(const b of bottles){updateFluid(b,step);syncBottleMass(b);}updateDrops(step);}},inspectHit:(index,energy,ballistic=false)=>{const b=bottles[index],brand=brands[b.idx];simTime+=.2;damageBottle(b,{energy,speed:Math.sqrt(energy*4),point:new THREE.Vector3(0,-brand.h*.20,brand.depth/2),other:null,ballistic});}};
// FPS / physics-cost overlay
(()=>{const el=document.createElement('div');el.style.cssText='position:fixed;left:8px;top:120px;z-index:9;font:12px monospace;color:#9f9;background:#0008;padding:4px 8px;pointer-events:none;white-space:pre';document.body.appendChild(el);let frames=0,last=performance.now();window.perfStat={phys:0,render:0,steps:0};
const origStep=world.step.bind(world);world.step=(...a)=>{const t=performance.now();origStep(...a);perfStat.phys+=performance.now()-t;perfStat.steps++;};
const origRender=renderer.render.bind(renderer);renderer.render=(...a)=>{const t=performance.now();origRender(...a);perfStat.render+=performance.now()-t;};
setInterval(()=>{const now=performance.now(),fps=frames*1000/(now-last);el.textContent=`FPS ${fps.toFixed(0)}\nphys ${(perfStat.phys/Math.max(1,frames)).toFixed(1)}ms/frame (${(perfStat.steps/Math.max(1,frames)).toFixed(1)} steps)\nrender ${(perfStat.render/Math.max(1,frames)).toFixed(1)}ms\nres x${pixelRatio.toFixed(2)}  calls ${renderer.info.render.calls}\nawake ${world.bodies.filter(b=>b.sleepState!==2).length}/${world.bodies.length}`;frames=0;last=now;perfStat.phys=perfStat.render=perfStat.steps=0;},500);
(function tick(){frames++;requestAnimationFrame(tick);})();})();
